version: '3.6'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  web:
    image: inventory-system
    links:
      - mongodb
    ports:
      - 3001:3001